# Site settings
title: "Chris Hallberg"
description: "Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Chris Hallberg, MD"
resume_title:                   "Resident Physician"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sample email"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-5555"
resume_contact_address:         "Street address"

resume_header_contact_info:     "street addres, city, state • 555-555555 • sample@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I'm a third-year resident in the Family Medicine Residency of Western Montana program out of Missoula, MT. I'm originally from Milwaukee, WI where I did undergrad at Marquette University prior to attending medical school at the University of Washington in Seattle. I plan to pursue a job in primary care somewhere in western Montana.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/challberg"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://chrishallberg.org"
  #resume_medium_url:            "https://medium.com/@"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
